name: "S3 Copy"
description: "Copy a directory in one S3 Bucket to another"
author: "Amihan, forked from jakejarvis"
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
